//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bonus.BusinessServices.WsBonusValidarAfiliacion {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="AppBonus", ConfigurationName="WsBonusValidarAfiliacion.wsconctaadSoapPort")]
    public interface wsconctaadSoapPort {
        
        [System.ServiceModel.OperationContractAttribute(Action="AppBonusaction/AWSCONCTAAD.Execute", ReplyAction="*")]
        Bonus.BusinessServices.WsBonusValidarAfiliacion.ExecuteResponse Execute(Bonus.BusinessServices.WsBonusValidarAfiliacion.ExecuteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="AppBonusaction/AWSCONCTAAD.Execute", ReplyAction="*")]
        System.Threading.Tasks.Task<Bonus.BusinessServices.WsBonusValidarAfiliacion.ExecuteResponse> ExecuteAsync(Bonus.BusinessServices.WsBonusValidarAfiliacion.ExecuteRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ExecuteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="wsconctaad.Execute", Namespace="AppBonus", Order=0)]
        public Bonus.BusinessServices.WsBonusValidarAfiliacion.ExecuteRequestBody Body;
        
        public ExecuteRequest() {
        }
        
        public ExecuteRequest(Bonus.BusinessServices.WsBonusValidarAfiliacion.ExecuteRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="AppBonus")]
    public partial class ExecuteRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Ctaprscod;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public short Ctacod;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Pctaasocod;
        
        public ExecuteRequestBody() {
        }
        
        public ExecuteRequestBody(string Ctaprscod, short Ctacod, string Pctaasocod) {
            this.Ctaprscod = Ctaprscod;
            this.Ctacod = Ctacod;
            this.Pctaasocod = Pctaasocod;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ExecuteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="wsconctaad.ExecuteResponse", Namespace="AppBonus", Order=0)]
        public Bonus.BusinessServices.WsBonusValidarAfiliacion.ExecuteResponseBody Body;
        
        public ExecuteResponse() {
        }
        
        public ExecuteResponse(Bonus.BusinessServices.WsBonusValidarAfiliacion.ExecuteResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="AppBonus")]
    public partial class ExecuteResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public short Coderror;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Msjerror;
        
        public ExecuteResponseBody() {
        }
        
        public ExecuteResponseBody(short Coderror, string Msjerror) {
            this.Coderror = Coderror;
            this.Msjerror = Msjerror;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface wsconctaadSoapPortChannel : Bonus.BusinessServices.WsBonusValidarAfiliacion.wsconctaadSoapPort, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class wsconctaadSoapPortClient : System.ServiceModel.ClientBase<Bonus.BusinessServices.WsBonusValidarAfiliacion.wsconctaadSoapPort>, Bonus.BusinessServices.WsBonusValidarAfiliacion.wsconctaadSoapPort {
        
        public wsconctaadSoapPortClient() {
        }
        
        public wsconctaadSoapPortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public wsconctaadSoapPortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsconctaadSoapPortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsconctaadSoapPortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Bonus.BusinessServices.WsBonusValidarAfiliacion.ExecuteResponse Bonus.BusinessServices.WsBonusValidarAfiliacion.wsconctaadSoapPort.Execute(Bonus.BusinessServices.WsBonusValidarAfiliacion.ExecuteRequest request) {
            return base.Channel.Execute(request);
        }
        
        public short Execute(string Ctaprscod, short Ctacod, string Pctaasocod, out string Msjerror) {
            Bonus.BusinessServices.WsBonusValidarAfiliacion.ExecuteRequest inValue = new Bonus.BusinessServices.WsBonusValidarAfiliacion.ExecuteRequest();
            inValue.Body = new Bonus.BusinessServices.WsBonusValidarAfiliacion.ExecuteRequestBody();
            inValue.Body.Ctaprscod = Ctaprscod;
            inValue.Body.Ctacod = Ctacod;
            inValue.Body.Pctaasocod = Pctaasocod;
            Bonus.BusinessServices.WsBonusValidarAfiliacion.ExecuteResponse retVal = ((Bonus.BusinessServices.WsBonusValidarAfiliacion.wsconctaadSoapPort)(this)).Execute(inValue);
            Msjerror = retVal.Body.Msjerror;
            return retVal.Body.Coderror;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Bonus.BusinessServices.WsBonusValidarAfiliacion.ExecuteResponse> Bonus.BusinessServices.WsBonusValidarAfiliacion.wsconctaadSoapPort.ExecuteAsync(Bonus.BusinessServices.WsBonusValidarAfiliacion.ExecuteRequest request) {
            return base.Channel.ExecuteAsync(request);
        }
        
        public System.Threading.Tasks.Task<Bonus.BusinessServices.WsBonusValidarAfiliacion.ExecuteResponse> ExecuteAsync(string Ctaprscod, short Ctacod, string Pctaasocod) {
            Bonus.BusinessServices.WsBonusValidarAfiliacion.ExecuteRequest inValue = new Bonus.BusinessServices.WsBonusValidarAfiliacion.ExecuteRequest();
            inValue.Body = new Bonus.BusinessServices.WsBonusValidarAfiliacion.ExecuteRequestBody();
            inValue.Body.Ctaprscod = Ctaprscod;
            inValue.Body.Ctacod = Ctacod;
            inValue.Body.Pctaasocod = Pctaasocod;
            return ((Bonus.BusinessServices.WsBonusValidarAfiliacion.wsconctaadSoapPort)(this)).ExecuteAsync(inValue);
        }
    }
}
