//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bonus.BusinessServices.WsBonusDistritos {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="AppBonus", ConfigurationName="WsBonusDistritos.wslisdisSoapPort")]
    public interface wslisdisSoapPort {
        
        // CODEGEN: Generating message contract since the wrapper name (wslisdis.Execute) of message ExecuteRequest does not match the default value (Execute)
        [System.ServiceModel.OperationContractAttribute(Action="AppBonusaction/AWSLISDIS.Execute", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Bonus.BusinessServices.WsBonusDistritos.ExecuteResponse Execute(Bonus.BusinessServices.WsBonusDistritos.ExecuteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="AppBonusaction/AWSLISDIS.Execute", ReplyAction="*")]
        System.Threading.Tasks.Task<Bonus.BusinessServices.WsBonusDistritos.ExecuteResponse> ExecuteAsync(Bonus.BusinessServices.WsBonusDistritos.ExecuteRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="Lisdis.LisdisItem", Namespace="AppBonus")]
    public partial class LisdisLisdisItem : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string distCodField;
        
        private string distDesField;
        
        private string distCodPosField;
        
        /// <remarks/>
        public string DistCod {
            get {
                return this.distCodField;
            }
            set {
                this.distCodField = value;
                this.RaisePropertyChanged("DistCod");
            }
        }
        
        /// <remarks/>
        public string DistDes {
            get {
                return this.distDesField;
            }
            set {
                this.distDesField = value;
                this.RaisePropertyChanged("DistDes");
            }
        }
        
        /// <remarks/>
        public string DistCodPos {
            get {
                return this.distCodPosField;
            }
            set {
                this.distCodPosField = value;
                this.RaisePropertyChanged("DistCodPos");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="wslisdis.Execute", WrapperNamespace="AppBonus", IsWrapped=true)]
    public partial class ExecuteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="AppBonus", Order=0)]
        public string Dptocod;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="AppBonus", Order=1)]
        public string Provcod;
        
        public ExecuteRequest() {
        }
        
        public ExecuteRequest(string Dptocod, string Provcod) {
            this.Dptocod = Dptocod;
            this.Provcod = Provcod;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="wslisdis.ExecuteResponse", WrapperNamespace="AppBonus", IsWrapped=true)]
    public partial class ExecuteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="AppBonus", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Bonus.BusinessServices.WsBonusDistritos.LisdisLisdisItem[] Lista;
        
        public ExecuteResponse() {
        }
        
        public ExecuteResponse(Bonus.BusinessServices.WsBonusDistritos.LisdisLisdisItem[] Lista) {
            this.Lista = Lista;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface wslisdisSoapPortChannel : Bonus.BusinessServices.WsBonusDistritos.wslisdisSoapPort, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class wslisdisSoapPortClient : System.ServiceModel.ClientBase<Bonus.BusinessServices.WsBonusDistritos.wslisdisSoapPort>, Bonus.BusinessServices.WsBonusDistritos.wslisdisSoapPort {
        
        public wslisdisSoapPortClient() {
        }
        
        public wslisdisSoapPortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public wslisdisSoapPortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wslisdisSoapPortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wslisdisSoapPortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Bonus.BusinessServices.WsBonusDistritos.ExecuteResponse Bonus.BusinessServices.WsBonusDistritos.wslisdisSoapPort.Execute(Bonus.BusinessServices.WsBonusDistritos.ExecuteRequest request) {
            return base.Channel.Execute(request);
        }
        
        public Bonus.BusinessServices.WsBonusDistritos.LisdisLisdisItem[] Execute(string Dptocod, string Provcod) {
            Bonus.BusinessServices.WsBonusDistritos.ExecuteRequest inValue = new Bonus.BusinessServices.WsBonusDistritos.ExecuteRequest();
            inValue.Dptocod = Dptocod;
            inValue.Provcod = Provcod;
            Bonus.BusinessServices.WsBonusDistritos.ExecuteResponse retVal = ((Bonus.BusinessServices.WsBonusDistritos.wslisdisSoapPort)(this)).Execute(inValue);
            return retVal.Lista;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Bonus.BusinessServices.WsBonusDistritos.ExecuteResponse> Bonus.BusinessServices.WsBonusDistritos.wslisdisSoapPort.ExecuteAsync(Bonus.BusinessServices.WsBonusDistritos.ExecuteRequest request) {
            return base.Channel.ExecuteAsync(request);
        }
        
        public System.Threading.Tasks.Task<Bonus.BusinessServices.WsBonusDistritos.ExecuteResponse> ExecuteAsync(string Dptocod, string Provcod) {
            Bonus.BusinessServices.WsBonusDistritos.ExecuteRequest inValue = new Bonus.BusinessServices.WsBonusDistritos.ExecuteRequest();
            inValue.Dptocod = Dptocod;
            inValue.Provcod = Provcod;
            return ((Bonus.BusinessServices.WsBonusDistritos.wslisdisSoapPort)(this)).ExecuteAsync(inValue);
        }
    }
}
