//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bonus.BusinessServices.WsBonusObtenerCountToken {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="AppBonus", ConfigurationName="WsBonusObtenerCountToken.wsobtcotokSoapPort")]
    public interface wsobtcotokSoapPort {
        
        [System.ServiceModel.OperationContractAttribute(Action="AppBonusaction/AWSOBTCOTOK.Execute", ReplyAction="*")]
        Bonus.BusinessServices.WsBonusObtenerCountToken.ExecuteResponse Execute(Bonus.BusinessServices.WsBonusObtenerCountToken.ExecuteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="AppBonusaction/AWSOBTCOTOK.Execute", ReplyAction="*")]
        System.Threading.Tasks.Task<Bonus.BusinessServices.WsBonusObtenerCountToken.ExecuteResponse> ExecuteAsync(Bonus.BusinessServices.WsBonusObtenerCountToken.ExecuteRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ExecuteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="wsobtcotok.Execute", Namespace="AppBonus", Order=0)]
        public Bonus.BusinessServices.WsBonusObtenerCountToken.ExecuteRequestBody Body;
        
        public ExecuteRequest() {
        }
        
        public ExecuteRequest(Bonus.BusinessServices.WsBonusObtenerCountToken.ExecuteRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="AppBonus")]
    public partial class ExecuteRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Authtoken;
        
        public ExecuteRequestBody() {
        }
        
        public ExecuteRequestBody(string Authtoken) {
            this.Authtoken = Authtoken;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ExecuteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="wsobtcotok.ExecuteResponse", Namespace="AppBonus", Order=0)]
        public Bonus.BusinessServices.WsBonusObtenerCountToken.ExecuteResponseBody Body;
        
        public ExecuteResponse() {
        }
        
        public ExecuteResponse(Bonus.BusinessServices.WsBonusObtenerCountToken.ExecuteResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="AppBonus")]
    public partial class ExecuteResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public short Count;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public short Coderror;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Msjerror;
        
        public ExecuteResponseBody() {
        }
        
        public ExecuteResponseBody(short Count, short Coderror, string Msjerror) {
            this.Count = Count;
            this.Coderror = Coderror;
            this.Msjerror = Msjerror;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface wsobtcotokSoapPortChannel : Bonus.BusinessServices.WsBonusObtenerCountToken.wsobtcotokSoapPort, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class wsobtcotokSoapPortClient : System.ServiceModel.ClientBase<Bonus.BusinessServices.WsBonusObtenerCountToken.wsobtcotokSoapPort>, Bonus.BusinessServices.WsBonusObtenerCountToken.wsobtcotokSoapPort {
        
        public wsobtcotokSoapPortClient() {
        }
        
        public wsobtcotokSoapPortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public wsobtcotokSoapPortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsobtcotokSoapPortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsobtcotokSoapPortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Bonus.BusinessServices.WsBonusObtenerCountToken.ExecuteResponse Bonus.BusinessServices.WsBonusObtenerCountToken.wsobtcotokSoapPort.Execute(Bonus.BusinessServices.WsBonusObtenerCountToken.ExecuteRequest request) {
            return base.Channel.Execute(request);
        }
        
        public short Execute(string Authtoken, out short Coderror, out string Msjerror) {
            Bonus.BusinessServices.WsBonusObtenerCountToken.ExecuteRequest inValue = new Bonus.BusinessServices.WsBonusObtenerCountToken.ExecuteRequest();
            inValue.Body = new Bonus.BusinessServices.WsBonusObtenerCountToken.ExecuteRequestBody();
            inValue.Body.Authtoken = Authtoken;
            Bonus.BusinessServices.WsBonusObtenerCountToken.ExecuteResponse retVal = ((Bonus.BusinessServices.WsBonusObtenerCountToken.wsobtcotokSoapPort)(this)).Execute(inValue);
            Coderror = retVal.Body.Coderror;
            Msjerror = retVal.Body.Msjerror;
            return retVal.Body.Count;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Bonus.BusinessServices.WsBonusObtenerCountToken.ExecuteResponse> Bonus.BusinessServices.WsBonusObtenerCountToken.wsobtcotokSoapPort.ExecuteAsync(Bonus.BusinessServices.WsBonusObtenerCountToken.ExecuteRequest request) {
            return base.Channel.ExecuteAsync(request);
        }
        
        public System.Threading.Tasks.Task<Bonus.BusinessServices.WsBonusObtenerCountToken.ExecuteResponse> ExecuteAsync(string Authtoken) {
            Bonus.BusinessServices.WsBonusObtenerCountToken.ExecuteRequest inValue = new Bonus.BusinessServices.WsBonusObtenerCountToken.ExecuteRequest();
            inValue.Body = new Bonus.BusinessServices.WsBonusObtenerCountToken.ExecuteRequestBody();
            inValue.Body.Authtoken = Authtoken;
            return ((Bonus.BusinessServices.WsBonusObtenerCountToken.wsobtcotokSoapPort)(this)).ExecuteAsync(inValue);
        }
    }
}
