//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bonus.BusinessServices.WsBonusInfoCuenta {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="AppBonus", ConfigurationName="WsBonusInfoCuenta.wslisctaptSoapPort")]
    public interface wslisctaptSoapPort {
        
        [System.ServiceModel.OperationContractAttribute(Action="AppBonusaction/AWSLISCTAPT.Execute", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Bonus.BusinessServices.WsBonusInfoCuenta.ExecuteResponse Execute(Bonus.BusinessServices.WsBonusInfoCuenta.ExecuteRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="AppBonusaction/AWSLISCTAPT.Execute", ReplyAction="*")]
        System.Threading.Tasks.Task<Bonus.BusinessServices.WsBonusInfoCuenta.ExecuteResponse> ExecuteAsync(Bonus.BusinessServices.WsBonusInfoCuenta.ExecuteRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="Lisctapto.LisctaptoItem", Namespace="AppBonus")]
    public partial class LisctaptoLisctaptoItem : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string ctaPrsCodField;
        
        private short ctaCodField;
        
        private string ctaPrsNomField;
        
        private string pCtaAsoCodField;
        
        private string ctaAsoNomField;
        
        private string pCtaTipField;
        
        private string pCtaTipNomField;
        
        private string pCtaAutCnjField;
        
        private short tipPunCodField;
        
        private double ctaSalVigField;
        
        private double ctaSalConField;
        
        private double ctaSalDspField;
        
        /// <remarks/>
        public string CtaPrsCod {
            get {
                return this.ctaPrsCodField;
            }
            set {
                this.ctaPrsCodField = value;
                this.RaisePropertyChanged("CtaPrsCod");
            }
        }
        
        /// <remarks/>
        public short CtaCod {
            get {
                return this.ctaCodField;
            }
            set {
                this.ctaCodField = value;
                this.RaisePropertyChanged("CtaCod");
            }
        }
        
        /// <remarks/>
        public string CtaPrsNom {
            get {
                return this.ctaPrsNomField;
            }
            set {
                this.ctaPrsNomField = value;
                this.RaisePropertyChanged("CtaPrsNom");
            }
        }
        
        /// <remarks/>
        public string PCtaAsoCod {
            get {
                return this.pCtaAsoCodField;
            }
            set {
                this.pCtaAsoCodField = value;
                this.RaisePropertyChanged("PCtaAsoCod");
            }
        }
        
        /// <remarks/>
        public string CtaAsoNom {
            get {
                return this.ctaAsoNomField;
            }
            set {
                this.ctaAsoNomField = value;
                this.RaisePropertyChanged("CtaAsoNom");
            }
        }
        
        /// <remarks/>
        public string PCtaTip {
            get {
                return this.pCtaTipField;
            }
            set {
                this.pCtaTipField = value;
                this.RaisePropertyChanged("PCtaTip");
            }
        }
        
        /// <remarks/>
        public string PCtaTipNom {
            get {
                return this.pCtaTipNomField;
            }
            set {
                this.pCtaTipNomField = value;
                this.RaisePropertyChanged("PCtaTipNom");
            }
        }
        
        /// <remarks/>
        public string PCtaAutCnj {
            get {
                return this.pCtaAutCnjField;
            }
            set {
                this.pCtaAutCnjField = value;
                this.RaisePropertyChanged("PCtaAutCnj");
            }
        }
        
        /// <remarks/>
        public short TipPunCod {
            get {
                return this.tipPunCodField;
            }
            set {
                this.tipPunCodField = value;
                this.RaisePropertyChanged("TipPunCod");
            }
        }
        
        /// <remarks/>
        public double CtaSalVig {
            get {
                return this.ctaSalVigField;
            }
            set {
                this.ctaSalVigField = value;
                this.RaisePropertyChanged("CtaSalVig");
            }
        }
        
        /// <remarks/>
        public double CtaSalCon {
            get {
                return this.ctaSalConField;
            }
            set {
                this.ctaSalConField = value;
                this.RaisePropertyChanged("CtaSalCon");
            }
        }
        
        /// <remarks/>
        public double CtaSalDsp {
            get {
                return this.ctaSalDspField;
            }
            set {
                this.ctaSalDspField = value;
                this.RaisePropertyChanged("CtaSalDsp");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="wslisctapt.Execute", WrapperNamespace="AppBonus", IsWrapped=true)]
    public partial class ExecuteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="AppBonus", Order=0)]
        public string Ctaprscod;
        
        public ExecuteRequest() {
        }
        
        public ExecuteRequest(string Ctaprscod) {
            this.Ctaprscod = Ctaprscod;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="wslisctapt.ExecuteResponse", WrapperNamespace="AppBonus", IsWrapped=true)]
    public partial class ExecuteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="AppBonus", Order=0)]
        public short Coderror;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="AppBonus", Order=1)]
        public string Msjerror;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="AppBonus", Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Bonus.BusinessServices.WsBonusInfoCuenta.LisctaptoLisctaptoItem[] Carritocta;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="AppBonus", Order=3)]
        public short Prstipdcod;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="AppBonus", Order=4)]
        public string Prsnrodoc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="AppBonus", Order=5)]
        public string Prsnomape;
        
        public ExecuteResponse() {
        }
        
        public ExecuteResponse(short Coderror, string Msjerror, Bonus.BusinessServices.WsBonusInfoCuenta.LisctaptoLisctaptoItem[] Carritocta, short Prstipdcod, string Prsnrodoc, string Prsnomape) {
            this.Coderror = Coderror;
            this.Msjerror = Msjerror;
            this.Carritocta = Carritocta;
            this.Prstipdcod = Prstipdcod;
            this.Prsnrodoc = Prsnrodoc;
            this.Prsnomape = Prsnomape;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface wslisctaptSoapPortChannel : Bonus.BusinessServices.WsBonusInfoCuenta.wslisctaptSoapPort, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class wslisctaptSoapPortClient : System.ServiceModel.ClientBase<Bonus.BusinessServices.WsBonusInfoCuenta.wslisctaptSoapPort>, Bonus.BusinessServices.WsBonusInfoCuenta.wslisctaptSoapPort {
        
        public wslisctaptSoapPortClient() {
        }
        
        public wslisctaptSoapPortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public wslisctaptSoapPortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wslisctaptSoapPortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wslisctaptSoapPortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Bonus.BusinessServices.WsBonusInfoCuenta.ExecuteResponse Bonus.BusinessServices.WsBonusInfoCuenta.wslisctaptSoapPort.Execute(Bonus.BusinessServices.WsBonusInfoCuenta.ExecuteRequest request) {
            return base.Channel.Execute(request);
        }
        
        public short Execute(string Ctaprscod, out string Msjerror, out Bonus.BusinessServices.WsBonusInfoCuenta.LisctaptoLisctaptoItem[] Carritocta, out short Prstipdcod, out string Prsnrodoc, out string Prsnomape) {
            Bonus.BusinessServices.WsBonusInfoCuenta.ExecuteRequest inValue = new Bonus.BusinessServices.WsBonusInfoCuenta.ExecuteRequest();
            inValue.Ctaprscod = Ctaprscod;
            Bonus.BusinessServices.WsBonusInfoCuenta.ExecuteResponse retVal = ((Bonus.BusinessServices.WsBonusInfoCuenta.wslisctaptSoapPort)(this)).Execute(inValue);
            Msjerror = retVal.Msjerror;
            Carritocta = retVal.Carritocta;
            Prstipdcod = retVal.Prstipdcod;
            Prsnrodoc = retVal.Prsnrodoc;
            Prsnomape = retVal.Prsnomape;
            return retVal.Coderror;
        }
        
        public System.Threading.Tasks.Task<Bonus.BusinessServices.WsBonusInfoCuenta.ExecuteResponse> ExecuteAsync(Bonus.BusinessServices.WsBonusInfoCuenta.ExecuteRequest request) {
            return base.Channel.ExecuteAsync(request);
        }
    }
}
