//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bonus.BusinessServices.WsBonusInsertarToken {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="AppBonus", ConfigurationName="WsBonusInsertarToken.wsinstokenSoapPort")]
    public interface wsinstokenSoapPort {
        
        [System.ServiceModel.OperationContractAttribute(Action="AppBonusaction/AWSINSTOKEN.Execute", ReplyAction="*")]
        Bonus.BusinessServices.WsBonusInsertarToken.ExecuteResponse Execute(Bonus.BusinessServices.WsBonusInsertarToken.ExecuteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="AppBonusaction/AWSINSTOKEN.Execute", ReplyAction="*")]
        System.Threading.Tasks.Task<Bonus.BusinessServices.WsBonusInsertarToken.ExecuteResponse> ExecuteAsync(Bonus.BusinessServices.WsBonusInsertarToken.ExecuteRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ExecuteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="wsinstoken.Execute", Namespace="AppBonus", Order=0)]
        public Bonus.BusinessServices.WsBonusInsertarToken.ExecuteRequestBody Body;
        
        public ExecuteRequest() {
        }
        
        public ExecuteRequest(Bonus.BusinessServices.WsBonusInsertarToken.ExecuteRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="AppBonus")]
    public partial class ExecuteRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Userid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Authtoken;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.DateTime Issuedon;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.DateTime Expireson;
        
        public ExecuteRequestBody() {
        }
        
        public ExecuteRequestBody(string Userid, string Authtoken, System.DateTime Issuedon, System.DateTime Expireson) {
            this.Userid = Userid;
            this.Authtoken = Authtoken;
            this.Issuedon = Issuedon;
            this.Expireson = Expireson;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ExecuteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="wsinstoken.ExecuteResponse", Namespace="AppBonus", Order=0)]
        public Bonus.BusinessServices.WsBonusInsertarToken.ExecuteResponseBody Body;
        
        public ExecuteResponse() {
        }
        
        public ExecuteResponse(Bonus.BusinessServices.WsBonusInsertarToken.ExecuteResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="AppBonus")]
    public partial class ExecuteResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public short Coderror;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Msjerror;
        
        public ExecuteResponseBody() {
        }
        
        public ExecuteResponseBody(short Coderror, string Msjerror) {
            this.Coderror = Coderror;
            this.Msjerror = Msjerror;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface wsinstokenSoapPortChannel : Bonus.BusinessServices.WsBonusInsertarToken.wsinstokenSoapPort, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class wsinstokenSoapPortClient : System.ServiceModel.ClientBase<Bonus.BusinessServices.WsBonusInsertarToken.wsinstokenSoapPort>, Bonus.BusinessServices.WsBonusInsertarToken.wsinstokenSoapPort {
        
        public wsinstokenSoapPortClient() {
        }
        
        public wsinstokenSoapPortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public wsinstokenSoapPortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsinstokenSoapPortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsinstokenSoapPortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Bonus.BusinessServices.WsBonusInsertarToken.ExecuteResponse Bonus.BusinessServices.WsBonusInsertarToken.wsinstokenSoapPort.Execute(Bonus.BusinessServices.WsBonusInsertarToken.ExecuteRequest request) {
            return base.Channel.Execute(request);
        }
        
        public short Execute(string Userid, string Authtoken, System.DateTime Issuedon, System.DateTime Expireson, out string Msjerror) {
            Bonus.BusinessServices.WsBonusInsertarToken.ExecuteRequest inValue = new Bonus.BusinessServices.WsBonusInsertarToken.ExecuteRequest();
            inValue.Body = new Bonus.BusinessServices.WsBonusInsertarToken.ExecuteRequestBody();
            inValue.Body.Userid = Userid;
            inValue.Body.Authtoken = Authtoken;
            inValue.Body.Issuedon = Issuedon;
            inValue.Body.Expireson = Expireson;
            Bonus.BusinessServices.WsBonusInsertarToken.ExecuteResponse retVal = ((Bonus.BusinessServices.WsBonusInsertarToken.wsinstokenSoapPort)(this)).Execute(inValue);
            Msjerror = retVal.Body.Msjerror;
            return retVal.Body.Coderror;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Bonus.BusinessServices.WsBonusInsertarToken.ExecuteResponse> Bonus.BusinessServices.WsBonusInsertarToken.wsinstokenSoapPort.ExecuteAsync(Bonus.BusinessServices.WsBonusInsertarToken.ExecuteRequest request) {
            return base.Channel.ExecuteAsync(request);
        }
        
        public System.Threading.Tasks.Task<Bonus.BusinessServices.WsBonusInsertarToken.ExecuteResponse> ExecuteAsync(string Userid, string Authtoken, System.DateTime Issuedon, System.DateTime Expireson) {
            Bonus.BusinessServices.WsBonusInsertarToken.ExecuteRequest inValue = new Bonus.BusinessServices.WsBonusInsertarToken.ExecuteRequest();
            inValue.Body = new Bonus.BusinessServices.WsBonusInsertarToken.ExecuteRequestBody();
            inValue.Body.Userid = Userid;
            inValue.Body.Authtoken = Authtoken;
            inValue.Body.Issuedon = Issuedon;
            inValue.Body.Expireson = Expireson;
            return ((Bonus.BusinessServices.WsBonusInsertarToken.wsinstokenSoapPort)(this)).ExecuteAsync(inValue);
        }
    }
}
