//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bonus.BusinessServices.WsBonusExisteClienteBonus {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="AppBonus", ConfigurationName="WsBonusExisteClienteBonus.wsexicliboSoapPort")]
    public interface wsexicliboSoapPort {
        
        [System.ServiceModel.OperationContractAttribute(Action="AppBonusaction/AWSEXICLIBO.Execute", ReplyAction="*")]
        Bonus.BusinessServices.WsBonusExisteClienteBonus.ExecuteResponse Execute(Bonus.BusinessServices.WsBonusExisteClienteBonus.ExecuteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="AppBonusaction/AWSEXICLIBO.Execute", ReplyAction="*")]
        System.Threading.Tasks.Task<Bonus.BusinessServices.WsBonusExisteClienteBonus.ExecuteResponse> ExecuteAsync(Bonus.BusinessServices.WsBonusExisteClienteBonus.ExecuteRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ExecuteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="wsexiclibo.Execute", Namespace="AppBonus", Order=0)]
        public Bonus.BusinessServices.WsBonusExisteClienteBonus.ExecuteRequestBody Body;
        
        public ExecuteRequest() {
        }
        
        public ExecuteRequest(Bonus.BusinessServices.WsBonusExisteClienteBonus.ExecuteRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="AppBonus")]
    public partial class ExecuteRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public short Tipdoccod;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Prsnrodoc;
        
        public ExecuteRequestBody() {
        }
        
        public ExecuteRequestBody(short Tipdoccod, string Prsnrodoc) {
            this.Tipdoccod = Tipdoccod;
            this.Prsnrodoc = Prsnrodoc;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ExecuteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="wsexiclibo.ExecuteResponse", Namespace="AppBonus", Order=0)]
        public Bonus.BusinessServices.WsBonusExisteClienteBonus.ExecuteResponseBody Body;
        
        public ExecuteResponse() {
        }
        
        public ExecuteResponse(Bonus.BusinessServices.WsBonusExisteClienteBonus.ExecuteResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="AppBonus")]
    public partial class ExecuteResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public short Coderror;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Msjerror;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Prscod;
        
        public ExecuteResponseBody() {
        }
        
        public ExecuteResponseBody(short Coderror, string Msjerror, string Prscod) {
            this.Coderror = Coderror;
            this.Msjerror = Msjerror;
            this.Prscod = Prscod;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface wsexicliboSoapPortChannel : Bonus.BusinessServices.WsBonusExisteClienteBonus.wsexicliboSoapPort, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class wsexicliboSoapPortClient : System.ServiceModel.ClientBase<Bonus.BusinessServices.WsBonusExisteClienteBonus.wsexicliboSoapPort>, Bonus.BusinessServices.WsBonusExisteClienteBonus.wsexicliboSoapPort {
        
        public wsexicliboSoapPortClient() {
        }
        
        public wsexicliboSoapPortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public wsexicliboSoapPortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsexicliboSoapPortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsexicliboSoapPortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Bonus.BusinessServices.WsBonusExisteClienteBonus.ExecuteResponse Bonus.BusinessServices.WsBonusExisteClienteBonus.wsexicliboSoapPort.Execute(Bonus.BusinessServices.WsBonusExisteClienteBonus.ExecuteRequest request) {
            return base.Channel.Execute(request);
        }
        
        public short Execute(short Tipdoccod, string Prsnrodoc, out string Msjerror, out string Prscod) {
            Bonus.BusinessServices.WsBonusExisteClienteBonus.ExecuteRequest inValue = new Bonus.BusinessServices.WsBonusExisteClienteBonus.ExecuteRequest();
            inValue.Body = new Bonus.BusinessServices.WsBonusExisteClienteBonus.ExecuteRequestBody();
            inValue.Body.Tipdoccod = Tipdoccod;
            inValue.Body.Prsnrodoc = Prsnrodoc;
            Bonus.BusinessServices.WsBonusExisteClienteBonus.ExecuteResponse retVal = ((Bonus.BusinessServices.WsBonusExisteClienteBonus.wsexicliboSoapPort)(this)).Execute(inValue);
            Msjerror = retVal.Body.Msjerror;
            Prscod = retVal.Body.Prscod;
            return retVal.Body.Coderror;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Bonus.BusinessServices.WsBonusExisteClienteBonus.ExecuteResponse> Bonus.BusinessServices.WsBonusExisteClienteBonus.wsexicliboSoapPort.ExecuteAsync(Bonus.BusinessServices.WsBonusExisteClienteBonus.ExecuteRequest request) {
            return base.Channel.ExecuteAsync(request);
        }
        
        public System.Threading.Tasks.Task<Bonus.BusinessServices.WsBonusExisteClienteBonus.ExecuteResponse> ExecuteAsync(short Tipdoccod, string Prsnrodoc) {
            Bonus.BusinessServices.WsBonusExisteClienteBonus.ExecuteRequest inValue = new Bonus.BusinessServices.WsBonusExisteClienteBonus.ExecuteRequest();
            inValue.Body = new Bonus.BusinessServices.WsBonusExisteClienteBonus.ExecuteRequestBody();
            inValue.Body.Tipdoccod = Tipdoccod;
            inValue.Body.Prsnrodoc = Prsnrodoc;
            return ((Bonus.BusinessServices.WsBonusExisteClienteBonus.wsexicliboSoapPort)(this)).ExecuteAsync(inValue);
        }
    }
}
