//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bonus.BusinessServices.WsBonusDepartamentos {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="AppBonus", ConfigurationName="WsBonusDepartamentos.wslisdepSoapPort")]
    public interface wslisdepSoapPort {
        
        // CODEGEN: Generating message contract since the wrapper name (wslisdep.Execute) of message ExecuteRequest does not match the default value (Execute)
        [System.ServiceModel.OperationContractAttribute(Action="AppBonusaction/AWSLISDEP.Execute", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Bonus.BusinessServices.WsBonusDepartamentos.ExecuteResponse Execute(Bonus.BusinessServices.WsBonusDepartamentos.ExecuteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="AppBonusaction/AWSLISDEP.Execute", ReplyAction="*")]
        System.Threading.Tasks.Task<Bonus.BusinessServices.WsBonusDepartamentos.ExecuteResponse> ExecuteAsync(Bonus.BusinessServices.WsBonusDepartamentos.ExecuteRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="Lisdep.LisdepItem", Namespace="AppBonus")]
    public partial class LisdepLisdepItem : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string dptoCodField;
        
        private string dptoDesField;
        
        /// <remarks/>
        public string DptoCod {
            get {
                return this.dptoCodField;
            }
            set {
                this.dptoCodField = value;
                this.RaisePropertyChanged("DptoCod");
            }
        }
        
        /// <remarks/>
        public string DptoDes {
            get {
                return this.dptoDesField;
            }
            set {
                this.dptoDesField = value;
                this.RaisePropertyChanged("DptoDes");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="wslisdep.Execute", WrapperNamespace="AppBonus", IsWrapped=true)]
    public partial class ExecuteRequest {
        
        public ExecuteRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="wslisdep.ExecuteResponse", WrapperNamespace="AppBonus", IsWrapped=true)]
    public partial class ExecuteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="AppBonus", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Bonus.BusinessServices.WsBonusDepartamentos.LisdepLisdepItem[] Lista;
        
        public ExecuteResponse() {
        }
        
        public ExecuteResponse(Bonus.BusinessServices.WsBonusDepartamentos.LisdepLisdepItem[] Lista) {
            this.Lista = Lista;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface wslisdepSoapPortChannel : Bonus.BusinessServices.WsBonusDepartamentos.wslisdepSoapPort, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class wslisdepSoapPortClient : System.ServiceModel.ClientBase<Bonus.BusinessServices.WsBonusDepartamentos.wslisdepSoapPort>, Bonus.BusinessServices.WsBonusDepartamentos.wslisdepSoapPort {
        
        public wslisdepSoapPortClient() {
        }
        
        public wslisdepSoapPortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public wslisdepSoapPortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wslisdepSoapPortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wslisdepSoapPortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Bonus.BusinessServices.WsBonusDepartamentos.ExecuteResponse Bonus.BusinessServices.WsBonusDepartamentos.wslisdepSoapPort.Execute(Bonus.BusinessServices.WsBonusDepartamentos.ExecuteRequest request) {
            return base.Channel.Execute(request);
        }
        
        public Bonus.BusinessServices.WsBonusDepartamentos.LisdepLisdepItem[] Execute() {
            Bonus.BusinessServices.WsBonusDepartamentos.ExecuteRequest inValue = new Bonus.BusinessServices.WsBonusDepartamentos.ExecuteRequest();
            Bonus.BusinessServices.WsBonusDepartamentos.ExecuteResponse retVal = ((Bonus.BusinessServices.WsBonusDepartamentos.wslisdepSoapPort)(this)).Execute(inValue);
            return retVal.Lista;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Bonus.BusinessServices.WsBonusDepartamentos.ExecuteResponse> Bonus.BusinessServices.WsBonusDepartamentos.wslisdepSoapPort.ExecuteAsync(Bonus.BusinessServices.WsBonusDepartamentos.ExecuteRequest request) {
            return base.Channel.ExecuteAsync(request);
        }
        
        public System.Threading.Tasks.Task<Bonus.BusinessServices.WsBonusDepartamentos.ExecuteResponse> ExecuteAsync() {
            Bonus.BusinessServices.WsBonusDepartamentos.ExecuteRequest inValue = new Bonus.BusinessServices.WsBonusDepartamentos.ExecuteRequest();
            return ((Bonus.BusinessServices.WsBonusDepartamentos.wslisdepSoapPort)(this)).ExecuteAsync(inValue);
        }
    }
}
