//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bonus.BusinessServices.WsBonusActualizarToken {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="AppBonus", ConfigurationName="WsBonusActualizarToken.wsacttokenSoapPort")]
    public interface wsacttokenSoapPort {
        
        [System.ServiceModel.OperationContractAttribute(Action="AppBonusaction/AWSACTTOKEN.Execute", ReplyAction="*")]
        Bonus.BusinessServices.WsBonusActualizarToken.ExecuteResponse Execute(Bonus.BusinessServices.WsBonusActualizarToken.ExecuteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="AppBonusaction/AWSACTTOKEN.Execute", ReplyAction="*")]
        System.Threading.Tasks.Task<Bonus.BusinessServices.WsBonusActualizarToken.ExecuteResponse> ExecuteAsync(Bonus.BusinessServices.WsBonusActualizarToken.ExecuteRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ExecuteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="wsacttoken.Execute", Namespace="AppBonus", Order=0)]
        public Bonus.BusinessServices.WsBonusActualizarToken.ExecuteRequestBody Body;
        
        public ExecuteRequest() {
        }
        
        public ExecuteRequest(Bonus.BusinessServices.WsBonusActualizarToken.ExecuteRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="AppBonus")]
    public partial class ExecuteRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Authtoken;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.DateTime Expireson;
        
        public ExecuteRequestBody() {
        }
        
        public ExecuteRequestBody(string Authtoken, System.DateTime Expireson) {
            this.Authtoken = Authtoken;
            this.Expireson = Expireson;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ExecuteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="wsacttoken.ExecuteResponse", Namespace="AppBonus", Order=0)]
        public Bonus.BusinessServices.WsBonusActualizarToken.ExecuteResponseBody Body;
        
        public ExecuteResponse() {
        }
        
        public ExecuteResponse(Bonus.BusinessServices.WsBonusActualizarToken.ExecuteResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="AppBonus")]
    public partial class ExecuteResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public short Coderror;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Msjerror;
        
        public ExecuteResponseBody() {
        }
        
        public ExecuteResponseBody(short Coderror, string Msjerror) {
            this.Coderror = Coderror;
            this.Msjerror = Msjerror;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface wsacttokenSoapPortChannel : Bonus.BusinessServices.WsBonusActualizarToken.wsacttokenSoapPort, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class wsacttokenSoapPortClient : System.ServiceModel.ClientBase<Bonus.BusinessServices.WsBonusActualizarToken.wsacttokenSoapPort>, Bonus.BusinessServices.WsBonusActualizarToken.wsacttokenSoapPort {
        
        public wsacttokenSoapPortClient() {
        }
        
        public wsacttokenSoapPortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public wsacttokenSoapPortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsacttokenSoapPortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsacttokenSoapPortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Bonus.BusinessServices.WsBonusActualizarToken.ExecuteResponse Bonus.BusinessServices.WsBonusActualizarToken.wsacttokenSoapPort.Execute(Bonus.BusinessServices.WsBonusActualizarToken.ExecuteRequest request) {
            return base.Channel.Execute(request);
        }
        
        public short Execute(string Authtoken, System.DateTime Expireson, out string Msjerror) {
            Bonus.BusinessServices.WsBonusActualizarToken.ExecuteRequest inValue = new Bonus.BusinessServices.WsBonusActualizarToken.ExecuteRequest();
            inValue.Body = new Bonus.BusinessServices.WsBonusActualizarToken.ExecuteRequestBody();
            inValue.Body.Authtoken = Authtoken;
            inValue.Body.Expireson = Expireson;
            Bonus.BusinessServices.WsBonusActualizarToken.ExecuteResponse retVal = ((Bonus.BusinessServices.WsBonusActualizarToken.wsacttokenSoapPort)(this)).Execute(inValue);
            Msjerror = retVal.Body.Msjerror;
            return retVal.Body.Coderror;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Bonus.BusinessServices.WsBonusActualizarToken.ExecuteResponse> Bonus.BusinessServices.WsBonusActualizarToken.wsacttokenSoapPort.ExecuteAsync(Bonus.BusinessServices.WsBonusActualizarToken.ExecuteRequest request) {
            return base.Channel.ExecuteAsync(request);
        }
        
        public System.Threading.Tasks.Task<Bonus.BusinessServices.WsBonusActualizarToken.ExecuteResponse> ExecuteAsync(string Authtoken, System.DateTime Expireson) {
            Bonus.BusinessServices.WsBonusActualizarToken.ExecuteRequest inValue = new Bonus.BusinessServices.WsBonusActualizarToken.ExecuteRequest();
            inValue.Body = new Bonus.BusinessServices.WsBonusActualizarToken.ExecuteRequestBody();
            inValue.Body.Authtoken = Authtoken;
            inValue.Body.Expireson = Expireson;
            return ((Bonus.BusinessServices.WsBonusActualizarToken.wsacttokenSoapPort)(this)).ExecuteAsync(inValue);
        }
    }
}
