//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bonus.BusinessServices.WsBonusClientesDatos {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="AppBonus", ConfigurationName="WsBonusClientesDatos.wsdevdatcoSoapPort")]
    public interface wsdevdatcoSoapPort {
        
        [System.ServiceModel.OperationContractAttribute(Action="AppBonusaction/AWSDEVDATCO.Execute", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Bonus.BusinessServices.WsBonusClientesDatos.ExecuteResponse Execute(Bonus.BusinessServices.WsBonusClientesDatos.ExecuteRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="AppBonusaction/AWSDEVDATCO.Execute", ReplyAction="*")]
        System.Threading.Tasks.Task<Bonus.BusinessServices.WsBonusClientesDatos.ExecuteResponse> ExecuteAsync(Bonus.BusinessServices.WsBonusClientesDatos.ExecuteRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="Lismai.LismaiItem", Namespace="AppBonus")]
    public partial class LismaiLismaiItem : object, System.ComponentModel.INotifyPropertyChanged {
        
        private sbyte prsMaiCodField;
        
        private string prsMaiField;
        
        private string prsFlgMErrField;
        
        /// <remarks/>
        public sbyte PrsMaiCod {
            get {
                return this.prsMaiCodField;
            }
            set {
                this.prsMaiCodField = value;
                this.RaisePropertyChanged("PrsMaiCod");
            }
        }
        
        /// <remarks/>
        public string PrsMai {
            get {
                return this.prsMaiField;
            }
            set {
                this.prsMaiField = value;
                this.RaisePropertyChanged("PrsMai");
            }
        }
        
        /// <remarks/>
        public string PrsFlgMErr {
            get {
                return this.prsFlgMErrField;
            }
            set {
                this.prsFlgMErrField = value;
                this.RaisePropertyChanged("PrsFlgMErr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="Lishij.LishijItem", Namespace="AppBonus")]
    public partial class LishijLishijItem : object, System.ComponentModel.INotifyPropertyChanged {
        
        private short prsHijEdaField;
        
        private string prsHijSexField;
        
        /// <remarks/>
        public short PrsHijEda {
            get {
                return this.prsHijEdaField;
            }
            set {
                this.prsHijEdaField = value;
                this.RaisePropertyChanged("PrsHijEda");
            }
        }
        
        /// <remarks/>
        public string PrsHijSex {
            get {
                return this.prsHijSexField;
            }
            set {
                this.prsHijSexField = value;
                this.RaisePropertyChanged("PrsHijSex");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="Listel.ListelItem", Namespace="AppBonus")]
    public partial class ListelListelItem : object, System.ComponentModel.INotifyPropertyChanged {
        
        private sbyte prsTlfCodField;
        
        private int prsPreTlfField;
        
        private long prsNroTlfField;
        
        private int prsAnxTlfField;
        
        private sbyte prsFlgMovField;
        
        private sbyte tlfRefCodField;
        
        private short otfCodField;
        
        private string prsRedPrvField;
        
        private string prsFlgTErrField;
        
        /// <remarks/>
        public sbyte PrsTlfCod {
            get {
                return this.prsTlfCodField;
            }
            set {
                this.prsTlfCodField = value;
                this.RaisePropertyChanged("PrsTlfCod");
            }
        }
        
        /// <remarks/>
        public int PrsPreTlf {
            get {
                return this.prsPreTlfField;
            }
            set {
                this.prsPreTlfField = value;
                this.RaisePropertyChanged("PrsPreTlf");
            }
        }
        
        /// <remarks/>
        public long PrsNroTlf {
            get {
                return this.prsNroTlfField;
            }
            set {
                this.prsNroTlfField = value;
                this.RaisePropertyChanged("PrsNroTlf");
            }
        }
        
        /// <remarks/>
        public int PrsAnxTlf {
            get {
                return this.prsAnxTlfField;
            }
            set {
                this.prsAnxTlfField = value;
                this.RaisePropertyChanged("PrsAnxTlf");
            }
        }
        
        /// <remarks/>
        public sbyte PrsFlgMov {
            get {
                return this.prsFlgMovField;
            }
            set {
                this.prsFlgMovField = value;
                this.RaisePropertyChanged("PrsFlgMov");
            }
        }
        
        /// <remarks/>
        public sbyte TlfRefCod {
            get {
                return this.tlfRefCodField;
            }
            set {
                this.tlfRefCodField = value;
                this.RaisePropertyChanged("TlfRefCod");
            }
        }
        
        /// <remarks/>
        public short OtfCod {
            get {
                return this.otfCodField;
            }
            set {
                this.otfCodField = value;
                this.RaisePropertyChanged("OtfCod");
            }
        }
        
        /// <remarks/>
        public string PrsRedPrv {
            get {
                return this.prsRedPrvField;
            }
            set {
                this.prsRedPrvField = value;
                this.RaisePropertyChanged("PrsRedPrv");
            }
        }
        
        /// <remarks/>
        public string PrsFlgTErr {
            get {
                return this.prsFlgTErrField;
            }
            set {
                this.prsFlgTErrField = value;
                this.RaisePropertyChanged("PrsFlgTErr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="wsdevdatco.Execute", WrapperNamespace="AppBonus", IsWrapped=true)]
    public partial class ExecuteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="AppBonus", Order=0)]
        public string Prscod;
        
        public ExecuteRequest() {
        }
        
        public ExecuteRequest(string Prscod) {
            this.Prscod = Prscod;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="wsdevdatco.ExecuteResponse", WrapperNamespace="AppBonus", IsWrapped=true)]
    public partial class ExecuteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="AppBonus", Order=0)]
        public string Prsapepat;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="AppBonus", Order=1)]
        public string Prsapemat;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="AppBonus", Order=2)]
        public string Prsprinom;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="AppBonus", Order=3)]
        public string Prssegnom;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="AppBonus", Order=4)]
        public string Prsternom;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="AppBonus", Order=5)]
        public short Tipdoccod;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="AppBonus", Order=6)]
        public string Prsnrodoc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="AppBonus", Order=7)]
        public string Prssex;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="AppBonus", Order=8)]
        public string Oprsfecnac;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="AppBonus", Order=9)]
        public string Nacprs;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="AppBonus", Order=10)]
        public string Texto1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="AppBonus", Order=11)]
        public string Texto2;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="AppBonus", Order=12)]
        public string Texto3;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="AppBonus", Order=13)]
        public string Texto4;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="AppBonus", Order=14)]
        public string Texto5;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="AppBonus", Order=15)]
        public string Datcor;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="AppBonus", Order=16)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Bonus.BusinessServices.WsBonusClientesDatos.LismaiLismaiItem[] Carritoco;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="AppBonus", Order=17)]
        public string Dattel;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="AppBonus", Order=18)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Bonus.BusinessServices.WsBonusClientesDatos.ListelListelItem[] Carritote;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="AppBonus", Order=19)]
        public string Direccion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="AppBonus", Order=20)]
        public string Referencia;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="AppBonus", Order=21)]
        public string Dptocod;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="AppBonus", Order=22)]
        public string Provcod;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="AppBonus", Order=23)]
        public string Distcod;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="AppBonus", Order=24)]
        public string Ocupacion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="AppBonus", Order=25)]
        public string Centrolabores;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="AppBonus", Order=26)]
        public string Clientepep;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="AppBonus", Order=27)]
        public string Cargopep;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="AppBonus", Order=28)]
        public string Flgtieveh;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="AppBonus", Order=29)]
        public string Flgtiehij;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="AppBonus", Order=30)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Bonus.BusinessServices.WsBonusClientesDatos.LishijLishijItem[] Carritohij;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="AppBonus", Order=31)]
        public short Coderror;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="AppBonus", Order=32)]
        public string Msjerror;
        
        public ExecuteResponse() {
        }
        
        public ExecuteResponse(
                    string Prsapepat, 
                    string Prsapemat, 
                    string Prsprinom, 
                    string Prssegnom, 
                    string Prsternom, 
                    short Tipdoccod, 
                    string Prsnrodoc, 
                    string Prssex, 
                    string Oprsfecnac, 
                    string Nacprs, 
                    string Texto1, 
                    string Texto2, 
                    string Texto3, 
                    string Texto4, 
                    string Texto5, 
                    string Datcor, 
                    Bonus.BusinessServices.WsBonusClientesDatos.LismaiLismaiItem[] Carritoco, 
                    string Dattel, 
                    Bonus.BusinessServices.WsBonusClientesDatos.ListelListelItem[] Carritote, 
                    string Direccion, 
                    string Referencia, 
                    string Dptocod, 
                    string Provcod, 
                    string Distcod, 
                    string Ocupacion, 
                    string Centrolabores, 
                    string Clientepep, 
                    string Cargopep, 
                    string Flgtieveh, 
                    string Flgtiehij, 
                    Bonus.BusinessServices.WsBonusClientesDatos.LishijLishijItem[] Carritohij, 
                    short Coderror, 
                    string Msjerror) {
            this.Prsapepat = Prsapepat;
            this.Prsapemat = Prsapemat;
            this.Prsprinom = Prsprinom;
            this.Prssegnom = Prssegnom;
            this.Prsternom = Prsternom;
            this.Tipdoccod = Tipdoccod;
            this.Prsnrodoc = Prsnrodoc;
            this.Prssex = Prssex;
            this.Oprsfecnac = Oprsfecnac;
            this.Nacprs = Nacprs;
            this.Texto1 = Texto1;
            this.Texto2 = Texto2;
            this.Texto3 = Texto3;
            this.Texto4 = Texto4;
            this.Texto5 = Texto5;
            this.Datcor = Datcor;
            this.Carritoco = Carritoco;
            this.Dattel = Dattel;
            this.Carritote = Carritote;
            this.Direccion = Direccion;
            this.Referencia = Referencia;
            this.Dptocod = Dptocod;
            this.Provcod = Provcod;
            this.Distcod = Distcod;
            this.Ocupacion = Ocupacion;
            this.Centrolabores = Centrolabores;
            this.Clientepep = Clientepep;
            this.Cargopep = Cargopep;
            this.Flgtieveh = Flgtieveh;
            this.Flgtiehij = Flgtiehij;
            this.Carritohij = Carritohij;
            this.Coderror = Coderror;
            this.Msjerror = Msjerror;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface wsdevdatcoSoapPortChannel : Bonus.BusinessServices.WsBonusClientesDatos.wsdevdatcoSoapPort, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class wsdevdatcoSoapPortClient : System.ServiceModel.ClientBase<Bonus.BusinessServices.WsBonusClientesDatos.wsdevdatcoSoapPort>, Bonus.BusinessServices.WsBonusClientesDatos.wsdevdatcoSoapPort {
        
        public wsdevdatcoSoapPortClient() {
        }
        
        public wsdevdatcoSoapPortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public wsdevdatcoSoapPortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsdevdatcoSoapPortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsdevdatcoSoapPortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Bonus.BusinessServices.WsBonusClientesDatos.ExecuteResponse Bonus.BusinessServices.WsBonusClientesDatos.wsdevdatcoSoapPort.Execute(Bonus.BusinessServices.WsBonusClientesDatos.ExecuteRequest request) {
            return base.Channel.Execute(request);
        }
        
        public string Execute(
                    string Prscod, 
                    out string Prsapemat, 
                    out string Prsprinom, 
                    out string Prssegnom, 
                    out string Prsternom, 
                    out short Tipdoccod, 
                    out string Prsnrodoc, 
                    out string Prssex, 
                    out string Oprsfecnac, 
                    out string Nacprs, 
                    out string Texto1, 
                    out string Texto2, 
                    out string Texto3, 
                    out string Texto4, 
                    out string Texto5, 
                    out string Datcor, 
                    out Bonus.BusinessServices.WsBonusClientesDatos.LismaiLismaiItem[] Carritoco, 
                    out string Dattel, 
                    out Bonus.BusinessServices.WsBonusClientesDatos.ListelListelItem[] Carritote, 
                    out string Direccion, 
                    out string Referencia, 
                    out string Dptocod, 
                    out string Provcod, 
                    out string Distcod, 
                    out string Ocupacion, 
                    out string Centrolabores, 
                    out string Clientepep, 
                    out string Cargopep, 
                    out string Flgtieveh, 
                    out string Flgtiehij, 
                    out Bonus.BusinessServices.WsBonusClientesDatos.LishijLishijItem[] Carritohij, 
                    out short Coderror, 
                    out string Msjerror) {
            Bonus.BusinessServices.WsBonusClientesDatos.ExecuteRequest inValue = new Bonus.BusinessServices.WsBonusClientesDatos.ExecuteRequest();
            inValue.Prscod = Prscod;
            Bonus.BusinessServices.WsBonusClientesDatos.ExecuteResponse retVal = ((Bonus.BusinessServices.WsBonusClientesDatos.wsdevdatcoSoapPort)(this)).Execute(inValue);
            Prsapemat = retVal.Prsapemat;
            Prsprinom = retVal.Prsprinom;
            Prssegnom = retVal.Prssegnom;
            Prsternom = retVal.Prsternom;
            Tipdoccod = retVal.Tipdoccod;
            Prsnrodoc = retVal.Prsnrodoc;
            Prssex = retVal.Prssex;
            Oprsfecnac = retVal.Oprsfecnac;
            Nacprs = retVal.Nacprs;
            Texto1 = retVal.Texto1;
            Texto2 = retVal.Texto2;
            Texto3 = retVal.Texto3;
            Texto4 = retVal.Texto4;
            Texto5 = retVal.Texto5;
            Datcor = retVal.Datcor;
            Carritoco = retVal.Carritoco;
            Dattel = retVal.Dattel;
            Carritote = retVal.Carritote;
            Direccion = retVal.Direccion;
            Referencia = retVal.Referencia;
            Dptocod = retVal.Dptocod;
            Provcod = retVal.Provcod;
            Distcod = retVal.Distcod;
            Ocupacion = retVal.Ocupacion;
            Centrolabores = retVal.Centrolabores;
            Clientepep = retVal.Clientepep;
            Cargopep = retVal.Cargopep;
            Flgtieveh = retVal.Flgtieveh;
            Flgtiehij = retVal.Flgtiehij;
            Carritohij = retVal.Carritohij;
            Coderror = retVal.Coderror;
            Msjerror = retVal.Msjerror;
            return retVal.Prsapepat;
        }
        
        public System.Threading.Tasks.Task<Bonus.BusinessServices.WsBonusClientesDatos.ExecuteResponse> ExecuteAsync(Bonus.BusinessServices.WsBonusClientesDatos.ExecuteRequest request) {
            return base.Channel.ExecuteAsync(request);
        }
    }
}
