//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bonus.BusinessServices.WsBonusProvincias {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="AppBonus", ConfigurationName="WsBonusProvincias.wslisproSoapPort")]
    public interface wslisproSoapPort {
        
        // CODEGEN: Generating message contract since the wrapper name (wslispro.Execute) of message ExecuteRequest does not match the default value (Execute)
        [System.ServiceModel.OperationContractAttribute(Action="AppBonusaction/AWSLISPRO.Execute", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Bonus.BusinessServices.WsBonusProvincias.ExecuteResponse Execute(Bonus.BusinessServices.WsBonusProvincias.ExecuteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="AppBonusaction/AWSLISPRO.Execute", ReplyAction="*")]
        System.Threading.Tasks.Task<Bonus.BusinessServices.WsBonusProvincias.ExecuteResponse> ExecuteAsync(Bonus.BusinessServices.WsBonusProvincias.ExecuteRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="Lispro.LisproItem", Namespace="AppBonus")]
    public partial class LisproLisproItem : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string provCodField;
        
        private string provDesField;
        
        /// <remarks/>
        public string ProvCod {
            get {
                return this.provCodField;
            }
            set {
                this.provCodField = value;
                this.RaisePropertyChanged("ProvCod");
            }
        }
        
        /// <remarks/>
        public string ProvDes {
            get {
                return this.provDesField;
            }
            set {
                this.provDesField = value;
                this.RaisePropertyChanged("ProvDes");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="wslispro.Execute", WrapperNamespace="AppBonus", IsWrapped=true)]
    public partial class ExecuteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="AppBonus", Order=0)]
        public string Dptocod;
        
        public ExecuteRequest() {
        }
        
        public ExecuteRequest(string Dptocod) {
            this.Dptocod = Dptocod;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="wslispro.ExecuteResponse", WrapperNamespace="AppBonus", IsWrapped=true)]
    public partial class ExecuteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="AppBonus", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Bonus.BusinessServices.WsBonusProvincias.LisproLisproItem[] Lista;
        
        public ExecuteResponse() {
        }
        
        public ExecuteResponse(Bonus.BusinessServices.WsBonusProvincias.LisproLisproItem[] Lista) {
            this.Lista = Lista;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface wslisproSoapPortChannel : Bonus.BusinessServices.WsBonusProvincias.wslisproSoapPort, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class wslisproSoapPortClient : System.ServiceModel.ClientBase<Bonus.BusinessServices.WsBonusProvincias.wslisproSoapPort>, Bonus.BusinessServices.WsBonusProvincias.wslisproSoapPort {
        
        public wslisproSoapPortClient() {
        }
        
        public wslisproSoapPortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public wslisproSoapPortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wslisproSoapPortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wslisproSoapPortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Bonus.BusinessServices.WsBonusProvincias.ExecuteResponse Bonus.BusinessServices.WsBonusProvincias.wslisproSoapPort.Execute(Bonus.BusinessServices.WsBonusProvincias.ExecuteRequest request) {
            return base.Channel.Execute(request);
        }
        
        public Bonus.BusinessServices.WsBonusProvincias.LisproLisproItem[] Execute(string Dptocod) {
            Bonus.BusinessServices.WsBonusProvincias.ExecuteRequest inValue = new Bonus.BusinessServices.WsBonusProvincias.ExecuteRequest();
            inValue.Dptocod = Dptocod;
            Bonus.BusinessServices.WsBonusProvincias.ExecuteResponse retVal = ((Bonus.BusinessServices.WsBonusProvincias.wslisproSoapPort)(this)).Execute(inValue);
            return retVal.Lista;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Bonus.BusinessServices.WsBonusProvincias.ExecuteResponse> Bonus.BusinessServices.WsBonusProvincias.wslisproSoapPort.ExecuteAsync(Bonus.BusinessServices.WsBonusProvincias.ExecuteRequest request) {
            return base.Channel.ExecuteAsync(request);
        }
        
        public System.Threading.Tasks.Task<Bonus.BusinessServices.WsBonusProvincias.ExecuteResponse> ExecuteAsync(string Dptocod) {
            Bonus.BusinessServices.WsBonusProvincias.ExecuteRequest inValue = new Bonus.BusinessServices.WsBonusProvincias.ExecuteRequest();
            inValue.Dptocod = Dptocod;
            return ((Bonus.BusinessServices.WsBonusProvincias.wslisproSoapPort)(this)).ExecuteAsync(inValue);
        }
    }
}
