//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bonus.BusinessServices.WsBonusCodigoPromocional {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="AppBonus", ConfigurationName="WsBonusCodigoPromocional.wsvalpromSoapPort")]
    public interface wsvalpromSoapPort {
        
        [System.ServiceModel.OperationContractAttribute(Action="AppBonusaction/AWSVALPROM.Execute", ReplyAction="*")]
        Bonus.BusinessServices.WsBonusCodigoPromocional.ExecuteResponse Execute(Bonus.BusinessServices.WsBonusCodigoPromocional.ExecuteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="AppBonusaction/AWSVALPROM.Execute", ReplyAction="*")]
        System.Threading.Tasks.Task<Bonus.BusinessServices.WsBonusCodigoPromocional.ExecuteResponse> ExecuteAsync(Bonus.BusinessServices.WsBonusCodigoPromocional.ExecuteRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ExecuteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="wsvalprom.Execute", Namespace="AppBonus", Order=0)]
        public Bonus.BusinessServices.WsBonusCodigoPromocional.ExecuteRequestBody Body;
        
        public ExecuteRequest() {
        }
        
        public ExecuteRequest(Bonus.BusinessServices.WsBonusCodigoPromocional.ExecuteRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="AppBonus")]
    public partial class ExecuteRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long Codprom;
        
        public ExecuteRequestBody() {
        }
        
        public ExecuteRequestBody(long Codprom) {
            this.Codprom = Codprom;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ExecuteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="wsvalprom.ExecuteResponse", Namespace="AppBonus", Order=0)]
        public Bonus.BusinessServices.WsBonusCodigoPromocional.ExecuteResponseBody Body;
        
        public ExecuteResponse() {
        }
        
        public ExecuteResponse(Bonus.BusinessServices.WsBonusCodigoPromocional.ExecuteResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="AppBonus")]
    public partial class ExecuteResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public short Coderror;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Msjerror;
        
        public ExecuteResponseBody() {
        }
        
        public ExecuteResponseBody(short Coderror, string Msjerror) {
            this.Coderror = Coderror;
            this.Msjerror = Msjerror;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface wsvalpromSoapPortChannel : Bonus.BusinessServices.WsBonusCodigoPromocional.wsvalpromSoapPort, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class wsvalpromSoapPortClient : System.ServiceModel.ClientBase<Bonus.BusinessServices.WsBonusCodigoPromocional.wsvalpromSoapPort>, Bonus.BusinessServices.WsBonusCodigoPromocional.wsvalpromSoapPort {
        
        public wsvalpromSoapPortClient() {
        }
        
        public wsvalpromSoapPortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public wsvalpromSoapPortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsvalpromSoapPortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsvalpromSoapPortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Bonus.BusinessServices.WsBonusCodigoPromocional.ExecuteResponse Bonus.BusinessServices.WsBonusCodigoPromocional.wsvalpromSoapPort.Execute(Bonus.BusinessServices.WsBonusCodigoPromocional.ExecuteRequest request) {
            return base.Channel.Execute(request);
        }
        
        public short Execute(long Codprom, out string Msjerror) {
            Bonus.BusinessServices.WsBonusCodigoPromocional.ExecuteRequest inValue = new Bonus.BusinessServices.WsBonusCodigoPromocional.ExecuteRequest();
            inValue.Body = new Bonus.BusinessServices.WsBonusCodigoPromocional.ExecuteRequestBody();
            inValue.Body.Codprom = Codprom;
            Bonus.BusinessServices.WsBonusCodigoPromocional.ExecuteResponse retVal = ((Bonus.BusinessServices.WsBonusCodigoPromocional.wsvalpromSoapPort)(this)).Execute(inValue);
            Msjerror = retVal.Body.Msjerror;
            return retVal.Body.Coderror;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Bonus.BusinessServices.WsBonusCodigoPromocional.ExecuteResponse> Bonus.BusinessServices.WsBonusCodigoPromocional.wsvalpromSoapPort.ExecuteAsync(Bonus.BusinessServices.WsBonusCodigoPromocional.ExecuteRequest request) {
            return base.Channel.ExecuteAsync(request);
        }
        
        public System.Threading.Tasks.Task<Bonus.BusinessServices.WsBonusCodigoPromocional.ExecuteResponse> ExecuteAsync(long Codprom) {
            Bonus.BusinessServices.WsBonusCodigoPromocional.ExecuteRequest inValue = new Bonus.BusinessServices.WsBonusCodigoPromocional.ExecuteRequest();
            inValue.Body = new Bonus.BusinessServices.WsBonusCodigoPromocional.ExecuteRequestBody();
            inValue.Body.Codprom = Codprom;
            return ((Bonus.BusinessServices.WsBonusCodigoPromocional.wsvalpromSoapPort)(this)).ExecuteAsync(inValue);
        }
    }
}
