//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bonus.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class inspeccion
    {
        public inspeccion()
        {
            this.foto = new HashSet<foto>();
            this.usuario_inspeccion = new HashSet<usuario_inspeccion>();
        }
    
        public int id { get; set; }
        public string descripcion { get; set; }
        public string cliente { get; set; }
        public string latitud { get; set; }
        public string longitud { get; set; }
    
        public virtual ICollection<foto> foto { get; set; }
        public virtual ICollection<usuario_inspeccion> usuario_inspeccion { get; set; }
    }
}
