//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bonus.DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GestionOperacionDbEntities : DbContext
    {
        public GestionOperacionDbEntities()
            : base("name=GestionOperacionDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<foto> foto { get; set; }
        public DbSet<inspeccion> inspeccion { get; set; }
        public DbSet<orden> orden { get; set; }
        public DbSet<rol> rol { get; set; }
        public DbSet<token> token { get; set; }
        public DbSet<usuario> usuario { get; set; }
    }
}
