//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bonus.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class token
    {
        public int id { get; set; }
        public string authToken { get; set; }
        public Nullable<System.DateTime> issuedOn { get; set; }
        public Nullable<System.DateTime> expiresOn { get; set; }
        public int userId { get; set; }
    
        public virtual usuario usuario { get; set; }
    }
}
