//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bonus.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario
    {
        public usuario()
        {
            this.orden = new HashSet<orden>();
            this.token = new HashSet<token>();
            this.rol = new HashSet<rol>();
        }
    
        public int id { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public string correo { get; set; }
        public string password { get; set; }
        public string telefono { get; set; }
        public int estado { get; set; }
    
        public virtual ICollection<orden> orden { get; set; }
        public virtual ICollection<token> token { get; set; }
        public virtual ICollection<rol> rol { get; set; }
    }
}
