//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bonus.DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class gestion_operaciones_dbEntities : DbContext
    {
        public gestion_operaciones_dbEntities()
            : base("name=gestion_operaciones_dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<autoridad> autoridad { get; set; }
        public DbSet<token> token { get; set; }
        public DbSet<usuario> usuario { get; set; }
    }
}
