//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bonus.BusinessServices.WsBonusEliminarToken {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="AppBonus", ConfigurationName="WsBonusEliminarToken.wselitokenSoapPort")]
    public interface wselitokenSoapPort {
        
        [System.ServiceModel.OperationContractAttribute(Action="AppBonusaction/AWSELITOKEN.Execute", ReplyAction="*")]
        Bonus.BusinessServices.WsBonusEliminarToken.ExecuteResponse Execute(Bonus.BusinessServices.WsBonusEliminarToken.ExecuteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="AppBonusaction/AWSELITOKEN.Execute", ReplyAction="*")]
        System.Threading.Tasks.Task<Bonus.BusinessServices.WsBonusEliminarToken.ExecuteResponse> ExecuteAsync(Bonus.BusinessServices.WsBonusEliminarToken.ExecuteRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ExecuteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="wselitoken.Execute", Namespace="AppBonus", Order=0)]
        public Bonus.BusinessServices.WsBonusEliminarToken.ExecuteRequestBody Body;
        
        public ExecuteRequest() {
        }
        
        public ExecuteRequest(Bonus.BusinessServices.WsBonusEliminarToken.ExecuteRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="AppBonus")]
    public partial class ExecuteRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Authtoken;
        
        public ExecuteRequestBody() {
        }
        
        public ExecuteRequestBody(string Authtoken) {
            this.Authtoken = Authtoken;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ExecuteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="wselitoken.ExecuteResponse", Namespace="AppBonus", Order=0)]
        public Bonus.BusinessServices.WsBonusEliminarToken.ExecuteResponseBody Body;
        
        public ExecuteResponse() {
        }
        
        public ExecuteResponse(Bonus.BusinessServices.WsBonusEliminarToken.ExecuteResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="AppBonus")]
    public partial class ExecuteResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public short Coderror;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Msjerror;
        
        public ExecuteResponseBody() {
        }
        
        public ExecuteResponseBody(short Coderror, string Msjerror) {
            this.Coderror = Coderror;
            this.Msjerror = Msjerror;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface wselitokenSoapPortChannel : Bonus.BusinessServices.WsBonusEliminarToken.wselitokenSoapPort, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class wselitokenSoapPortClient : System.ServiceModel.ClientBase<Bonus.BusinessServices.WsBonusEliminarToken.wselitokenSoapPort>, Bonus.BusinessServices.WsBonusEliminarToken.wselitokenSoapPort {
        
        public wselitokenSoapPortClient() {
        }
        
        public wselitokenSoapPortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public wselitokenSoapPortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wselitokenSoapPortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wselitokenSoapPortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Bonus.BusinessServices.WsBonusEliminarToken.ExecuteResponse Bonus.BusinessServices.WsBonusEliminarToken.wselitokenSoapPort.Execute(Bonus.BusinessServices.WsBonusEliminarToken.ExecuteRequest request) {
            return base.Channel.Execute(request);
        }
        
        public short Execute(string Authtoken, out string Msjerror) {
            Bonus.BusinessServices.WsBonusEliminarToken.ExecuteRequest inValue = new Bonus.BusinessServices.WsBonusEliminarToken.ExecuteRequest();
            inValue.Body = new Bonus.BusinessServices.WsBonusEliminarToken.ExecuteRequestBody();
            inValue.Body.Authtoken = Authtoken;
            Bonus.BusinessServices.WsBonusEliminarToken.ExecuteResponse retVal = ((Bonus.BusinessServices.WsBonusEliminarToken.wselitokenSoapPort)(this)).Execute(inValue);
            Msjerror = retVal.Body.Msjerror;
            return retVal.Body.Coderror;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Bonus.BusinessServices.WsBonusEliminarToken.ExecuteResponse> Bonus.BusinessServices.WsBonusEliminarToken.wselitokenSoapPort.ExecuteAsync(Bonus.BusinessServices.WsBonusEliminarToken.ExecuteRequest request) {
            return base.Channel.ExecuteAsync(request);
        }
        
        public System.Threading.Tasks.Task<Bonus.BusinessServices.WsBonusEliminarToken.ExecuteResponse> ExecuteAsync(string Authtoken) {
            Bonus.BusinessServices.WsBonusEliminarToken.ExecuteRequest inValue = new Bonus.BusinessServices.WsBonusEliminarToken.ExecuteRequest();
            inValue.Body = new Bonus.BusinessServices.WsBonusEliminarToken.ExecuteRequestBody();
            inValue.Body.Authtoken = Authtoken;
            return ((Bonus.BusinessServices.WsBonusEliminarToken.wselitokenSoapPort)(this)).ExecuteAsync(inValue);
        }
    }
}
