//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bonus.BusinessServices.WsBonusObtenerToken {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="AppBonus", ConfigurationName="WsBonusObtenerToken.wsobttokenSoapPort")]
    public interface wsobttokenSoapPort {
        
        [System.ServiceModel.OperationContractAttribute(Action="AppBonusaction/AWSOBTTOKEN.Execute", ReplyAction="*")]
        Bonus.BusinessServices.WsBonusObtenerToken.ExecuteResponse Execute(Bonus.BusinessServices.WsBonusObtenerToken.ExecuteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="AppBonusaction/AWSOBTTOKEN.Execute", ReplyAction="*")]
        System.Threading.Tasks.Task<Bonus.BusinessServices.WsBonusObtenerToken.ExecuteResponse> ExecuteAsync(Bonus.BusinessServices.WsBonusObtenerToken.ExecuteRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ExecuteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="wsobttoken.Execute", Namespace="AppBonus", Order=0)]
        public Bonus.BusinessServices.WsBonusObtenerToken.ExecuteRequestBody Body;
        
        public ExecuteRequest() {
        }
        
        public ExecuteRequest(Bonus.BusinessServices.WsBonusObtenerToken.ExecuteRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="AppBonus")]
    public partial class ExecuteRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Authtoken;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.DateTime Currentdate;
        
        public ExecuteRequestBody() {
        }
        
        public ExecuteRequestBody(string Authtoken, System.DateTime Currentdate) {
            this.Authtoken = Authtoken;
            this.Currentdate = Currentdate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ExecuteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="wsobttoken.ExecuteResponse", Namespace="AppBonus", Order=0)]
        public Bonus.BusinessServices.WsBonusObtenerToken.ExecuteResponseBody Body;
        
        public ExecuteResponse() {
        }
        
        public ExecuteResponse(Bonus.BusinessServices.WsBonusObtenerToken.ExecuteResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="AppBonus")]
    public partial class ExecuteResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public short Coderror;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Msjerror;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int Tokenid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Userid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Oissuedon;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Oexpireson;
        
        public ExecuteResponseBody() {
        }
        
        public ExecuteResponseBody(short Coderror, string Msjerror, int Tokenid, string Userid, string Oissuedon, string Oexpireson) {
            this.Coderror = Coderror;
            this.Msjerror = Msjerror;
            this.Tokenid = Tokenid;
            this.Userid = Userid;
            this.Oissuedon = Oissuedon;
            this.Oexpireson = Oexpireson;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface wsobttokenSoapPortChannel : Bonus.BusinessServices.WsBonusObtenerToken.wsobttokenSoapPort, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class wsobttokenSoapPortClient : System.ServiceModel.ClientBase<Bonus.BusinessServices.WsBonusObtenerToken.wsobttokenSoapPort>, Bonus.BusinessServices.WsBonusObtenerToken.wsobttokenSoapPort {
        
        public wsobttokenSoapPortClient() {
        }
        
        public wsobttokenSoapPortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public wsobttokenSoapPortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsobttokenSoapPortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsobttokenSoapPortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Bonus.BusinessServices.WsBonusObtenerToken.ExecuteResponse Bonus.BusinessServices.WsBonusObtenerToken.wsobttokenSoapPort.Execute(Bonus.BusinessServices.WsBonusObtenerToken.ExecuteRequest request) {
            return base.Channel.Execute(request);
        }
        
        public short Execute(string Authtoken, System.DateTime Currentdate, out string Msjerror, out int Tokenid, out string Userid, out string Oissuedon, out string Oexpireson) {
            Bonus.BusinessServices.WsBonusObtenerToken.ExecuteRequest inValue = new Bonus.BusinessServices.WsBonusObtenerToken.ExecuteRequest();
            inValue.Body = new Bonus.BusinessServices.WsBonusObtenerToken.ExecuteRequestBody();
            inValue.Body.Authtoken = Authtoken;
            inValue.Body.Currentdate = Currentdate;
            Bonus.BusinessServices.WsBonusObtenerToken.ExecuteResponse retVal = ((Bonus.BusinessServices.WsBonusObtenerToken.wsobttokenSoapPort)(this)).Execute(inValue);
            Msjerror = retVal.Body.Msjerror;
            Tokenid = retVal.Body.Tokenid;
            Userid = retVal.Body.Userid;
            Oissuedon = retVal.Body.Oissuedon;
            Oexpireson = retVal.Body.Oexpireson;
            return retVal.Body.Coderror;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Bonus.BusinessServices.WsBonusObtenerToken.ExecuteResponse> Bonus.BusinessServices.WsBonusObtenerToken.wsobttokenSoapPort.ExecuteAsync(Bonus.BusinessServices.WsBonusObtenerToken.ExecuteRequest request) {
            return base.Channel.ExecuteAsync(request);
        }
        
        public System.Threading.Tasks.Task<Bonus.BusinessServices.WsBonusObtenerToken.ExecuteResponse> ExecuteAsync(string Authtoken, System.DateTime Currentdate) {
            Bonus.BusinessServices.WsBonusObtenerToken.ExecuteRequest inValue = new Bonus.BusinessServices.WsBonusObtenerToken.ExecuteRequest();
            inValue.Body = new Bonus.BusinessServices.WsBonusObtenerToken.ExecuteRequestBody();
            inValue.Body.Authtoken = Authtoken;
            inValue.Body.Currentdate = Currentdate;
            return ((Bonus.BusinessServices.WsBonusObtenerToken.wsobttokenSoapPort)(this)).ExecuteAsync(inValue);
        }
    }
}
